### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by davisagli**
Makes this package compatible with Python 3. Includes configuration to run tests on travis in multiple Python environments.

### CODE REVIEW

**Comment by jensens** [comment]
great! but we should at least increase the minor version number as well to 2.1.0 - because its not a bug fix but a fully backward compatible change, right? (see semantic versioning http://semver.org)

**Comment by davisagli** [comment]
Plone 4.3 tests: http://jenkins.plone.org/job/pull-request-4.3/108/
Plone 5.0 tests: http://jenkins.plone.org/job/pull-request-5.0/404/

**Comment by davisagli** [comment]
I bumped the version to 2.1.0.

What does the "pr rebase" tag mean?

**Comment by jensens** [comment]
``pr rebase`` means it needs a rebase with master in order to merge. I may have applied the wrong label, must be ``pr review``.

**Pull request merged**
